<Project Sdk="Microsoft.NET.Sdk.Web">
<PropertyGroup><TargetFramework>net8.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><UserSecretsId>EnglishLearningPlatform-local-dev</UserSecretsId></PropertyGroup>
<ItemGroup><PackageReference Include="CsvHelper" Version="33.0.1" /><ProjectReference Include="../EnglishLearning.Application/EnglishLearning.Application.csproj" /><ProjectReference Include="../EnglishLearning.Infrastructure/EnglishLearning.Infrastructure.csproj" /><PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.13" /></ItemGroup>
</Project>
